<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CishRunner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CishCompiler\CishCompiler.csproj" />
  </ItemGroup>

</Project>
